DEBUG = False
# Development only
DEBUG = False
import os
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_DATABASE_URI = "postgresql://postgres:password@localhost:5432/nftspace_db"
# if os.getenv('POSTGRES_DEFAULT_HOST') and os.getenv('POSTGRES_DEFAULT_PORT'):
#     SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_DEFAULT_USER}:{POSTGRES_DEFAULT_PASSWORD}@{POSTGRES_DEFAULT_HOST}:{POSTGRES_DEFAULT_PORT}/{POSTGRES_DEFAULT_DB}"
SECRET_KEY='thisissecret'