DEBUG = False
# Development only
DEBUG = False
import os
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_DATABASE_URI = "postgresql://postgres:password@localhost:5432/nftspace_db"
if os.getenv('POSTGRES_DEFAULT_HOST'):
    POSTGRES_DEFAULT_HOST = os.getenv('POSTGRES_DEFAULT_HOST')
    POSTGRES_DEFAULT_PORT = os.getenv('POSTGRES_DEFAULT_PORT', 5432)
    POSTGRES_DEFAULT_USER = os.getenv('POSTGRES_DEFAULT_PORT', 'postgres')
    POSTGRES_DEFAULT_PASSWORD = os.getenv('POSTGRES_DEFAULT_PASSWORD', 'postgres')
    POSTGRES_DEFAULT_DB = os.getenv('POSTGRES_DEFAULT_DB', 'nft-space')
    SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_DEFAULT_USER}:{POSTGRES_DEFAULT_PASSWORD}@{POSTGRES_DEFAULT_HOST}:{POSTGRES_DEFAULT_PORT}/{POSTGRES_DEFAULT_DB}"
SECRET_KEY='thisissecret'